/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GroundsRouteImport } from './routes/grounds'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroundsIndexRouteImport } from './routes/grounds.index'
import { Route as GroundsIdRouteImport } from './routes/grounds.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSlotsRouteImport } from './routes/admin.slots'
import { Route as AdminGroundsRouteImport } from './routes/admin.grounds'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GroundsRoute = GroundsRouteImport.update({
  id: '/grounds',
  path: '/grounds',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroundsIndexRoute = GroundsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GroundsRoute,
} as any)
const GroundsIdRoute = GroundsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GroundsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSlotsRoute = AdminSlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGroundsRoute = AdminGroundsRouteImport.update({
  id: '/grounds',
  path: '/grounds',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookings': typeof BookingsRoute
  '/contact': typeof ContactRoute
  '/grounds': typeof GroundsRouteWithChildren
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/grounds': typeof AdminGroundsRoute
  '/admin/slots': typeof AdminSlotsRoute
  '/admin/users': typeof AdminUsersRoute
  '/grounds/$id': typeof GroundsIdRoute
  '/grounds/': typeof GroundsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookings': typeof BookingsRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/grounds': typeof AdminGroundsRoute
  '/admin/slots': typeof AdminSlotsRoute
  '/admin/users': typeof AdminUsersRoute
  '/grounds/$id': typeof GroundsIdRoute
  '/grounds': typeof GroundsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookings': typeof BookingsRoute
  '/contact': typeof ContactRoute
  '/grounds': typeof GroundsRouteWithChildren
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/grounds': typeof AdminGroundsRoute
  '/admin/slots': typeof AdminSlotsRoute
  '/admin/users': typeof AdminUsersRoute
  '/grounds/$id': typeof GroundsIdRoute
  '/grounds/': typeof GroundsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/bookings'
    | '/contact'
    | '/grounds'
    | '/login'
    | '/payment'
    | '/profile'
    | '/register'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/grounds'
    | '/admin/slots'
    | '/admin/users'
    | '/grounds/$id'
    | '/grounds/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/bookings'
    | '/contact'
    | '/login'
    | '/payment'
    | '/profile'
    | '/register'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/grounds'
    | '/admin/slots'
    | '/admin/users'
    | '/grounds/$id'
    | '/grounds'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/bookings'
    | '/contact'
    | '/grounds'
    | '/login'
    | '/payment'
    | '/profile'
    | '/register'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/grounds'
    | '/admin/slots'
    | '/admin/users'
    | '/grounds/$id'
    | '/grounds/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookingsRoute: typeof BookingsRoute
  ContactRoute: typeof ContactRoute
  GroundsRoute: typeof GroundsRouteWithChildren
  LoginRoute: typeof LoginRoute
  PaymentRoute: typeof PaymentRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grounds': {
      id: '/grounds'
      path: '/grounds'
      fullPath: '/grounds'
      preLoaderRoute: typeof GroundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grounds/': {
      id: '/grounds/'
      path: '/'
      fullPath: '/grounds/'
      preLoaderRoute: typeof GroundsIndexRouteImport
      parentRoute: typeof GroundsRoute
    }
    '/grounds/$id': {
      id: '/grounds/$id'
      path: '/$id'
      fullPath: '/grounds/$id'
      preLoaderRoute: typeof GroundsIdRouteImport
      parentRoute: typeof GroundsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/slots': {
      id: '/admin/slots'
      path: '/slots'
      fullPath: '/admin/slots'
      preLoaderRoute: typeof AdminSlotsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/grounds': {
      id: '/admin/grounds'
      path: '/grounds'
      fullPath: '/admin/grounds'
      preLoaderRoute: typeof AdminGroundsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminGroundsRoute: typeof AdminGroundsRoute
  AdminSlotsRoute: typeof AdminSlotsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminGroundsRoute: AdminGroundsRoute,
  AdminSlotsRoute: AdminSlotsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface GroundsRouteChildren {
  GroundsIdRoute: typeof GroundsIdRoute
  GroundsIndexRoute: typeof GroundsIndexRoute
}

const GroundsRouteChildren: GroundsRouteChildren = {
  GroundsIdRoute: GroundsIdRoute,
  GroundsIndexRoute: GroundsIndexRoute,
}

const GroundsRouteWithChildren =
  GroundsRoute._addFileChildren(GroundsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BookingsRoute: BookingsRoute,
  ContactRoute: ContactRoute,
  GroundsRoute: GroundsRouteWithChildren,
  LoginRoute: LoginRoute,
  PaymentRoute: PaymentRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
